from . import calendar_event_custom
from . import slide_channel_custom
from . import res_partner_custom
from . import calendar_service
from . import category_service
from . import cronjob_settings
from . import moodle_category
from . import course_service
from . import user_service
from . import export_stats
from . import import_stats
from . import credentials
from . import connector
from . import constants
from . import utils
