# -*- coding: utf-8 -*-
{
    'name': 'Portal Unificado de Certificaciones y Diplomas',
    'version': '16.0.1.0.0',
    'summary': 'Centraliza diplomas, actas de TFM/TFG y solicitudes de certificados de notas en el portal del campus.',
    'category': 'Website',
    'author': 'iRG',
    'depends': [
        'website',
        'portal',
        'irg_generacion_diplomas',
        'irg_gradebook_certificates',
        'irg_tfm_acta_documento',
        'isep_website_custom',
        'irg_course_portal_tiles',
        'irg_stripe_subscriptions',
        'irg_certificate_partial',
    ],
    'data': [
        'views/portal_templates.xml',
        'views/campus_dashboard_override.xml',
        'views/res_partner_views.xml',
        'views/op_student_views.xml',
        'views/irg_certificate_request_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
