from . import product_category
from . import res_partner
from . import slide_channel
from . import op_admission
from . import sale_order
from . import product_template
from . import op_course
from . import op_batch
from . import op_admission_register
from . import auto_admission_required