# -*- coding: utf-8 -*-
{
    'name': 'Isep Website Sale Custom Address',
    'version': '16.1',
    'summary': """ Isep website sale custom Summary """,
    'author': 'Breithner Aquituari',
    'website': '',
    'category': 'Website',
    'depends': ['base',
                'isep_sale_subscription_custom',
                'isep_record_request',
                'isep_openeducat_sale',
                'website_sale_subscription',
                'website_sale', 'sale_temporal', 
                'isep_sign_sale', 
                'sign',
                'product', 
                'sale' ],
    "data": [
        "views/template.xml",
        "views/template_extra_info.xml",        
        "views/sale_temporal_recurrence_views.xml",
        "views/product_template_attribute_value_views.xml",
        "views/crm_team_views.xml",
        "data/automated_actions.xml",
        "data/mail_template.xml",
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
