from . import record_request
from . import record_request_line
from . import record_request_list
from . import record_request_list_line
from . import admission
from . import res_partner
from . import res_partner_document
from . import ir_attachment
from . import sale_order_line
