# -*- coding: utf-8 -*-
MAX_PAYLOAD_BYTES = 65536
MAX_HTML_CHARS = 32768
MAX_PAGE_SIZE = 100
DEFAULT_PAGE_SIZE = 20
MAX_TITLE_CHARS = 200
MAX_ATTACHMENT_BYTES = 32768
ALLOWED_ENVIRONMENTS = ('test', 'beta')
SECRET_TOKENS = (
    'password', 'token', 'secret', 'api_key', 'apikey', 'access_token',
    'refresh_token', 'private_key', 'authorization', 'wstoken', 'smtp_pass',
    'datas', 'raw', 'bin_size',
)

OPERATION_CODES = [
    ('irg_list_academic_periods', 'List academic periods'),
    ('irg_list_courses', 'List courses'),
    ('irg_get_course_overview', 'Get course overview'),
    ('irg_get_course_batches', 'Get course batches'),
    ('irg_list_subjects', 'List subjects'),
    ('irg_get_course_structure', 'Get course structure'),
    ('irg_get_slide', 'Get slide'),
    ('irg_get_admission_overview', 'Get admission overview'),
    ('irg_get_admission_subject_openings', 'Get admission subject openings'),
    ('irg_get_student_access', 'Get student access'),
    ('irg_get_student_academic_360', 'Get student academic 360'),
    ('irg_get_gradebook_summary', 'Get gradebook summary'),
    ('irg_get_moodle_sync_status', 'Get Moodle sync status'),
    ('irg_get_survey_structure', 'Get survey structure'),
    ('irg_get_academic_incidents', 'Get academic incidents'),
    ('irg_create_slide_draft', 'Create unpublished article slide'),
    ('irg_update_slide_draft', 'Update unpublished article slide'),
    ('irg_create_course_section', 'Create course section'),
    ('irg_reorder_course_section', 'Reorder course sections'),
    ('irg_publish_slide', 'Publish a reviewed slide'),
    ('irg_unpublish_slide', 'Unpublish a slide'),
    ('irg_approve_operation', 'Approve a previewed operation'),
    ('irg_reject_operation', 'Reject a previewed operation'),
    ('irg_preview_online_clone', 'Preview HomeClass to Online clone'),
    ('irg_apply_online_clone', 'Apply HomeClass to Online clone'),
    ('irg_preview_content_reconciliation', 'Preview Online content diff'),
    ('irg_apply_content_reconciliation', 'Apply allowed Online content copy'),
    ('irg_preview_subject_opening', 'Preview subject openings'),
    ('irg_apply_subject_opening', 'Apply subject openings'),
    ('irg_preview_access_reconciliation', 'Preview access memberships'),
    ('irg_apply_access_reconciliation', 'Apply access memberships'),
    ('irg_preview_enrollment', 'Preview official enrollment'),
    ('irg_apply_enrollment', 'Apply official enrollment'),
    ('irg_preview_withdrawal', 'Preview withdrawal side effects'),
    ('irg_apply_withdrawal', 'Withdrawal (refused; use official UI)'),
    ('irg_get_access_exceptions', 'List access exceptions'),
    ('irg_get_batch_schedule', 'Read batch subject schedule'),
    ('irg_preview_batch_schedule_sync', 'Preview batch schedule writes'),
    ('irg_apply_batch_schedule_sync', 'Apply batch schedule writes'),
    ('irg_preview_subject_precedence', 'Preview subject precedence'),
    ('irg_get_student_subject_eligibility', 'Read can_be_taken evidence'),
    ('irg_preview_moodle_course_mapping', 'Preview Moodle subject maps'),
    ('irg_apply_moodle_course_mapping', 'Apply explicit Moodle subject maps'),
    ('irg_preview_moodle_grade_sync', 'Preview Moodle grade sync'),
    ('irg_apply_moodle_grade_sync', 'Apply official Moodle grade sync'),
    ('irg_confirm_moodle_student_match', 'Confirm one Moodle student match'),
    ('irg_get_student_grade_evidence', 'Read source grade evidence'),
    ('irg_create_survey_draft', 'Create unpublished survey'),
    ('irg_update_survey_draft', 'Update unpublished survey title'),
    ('irg_preview_auto_score', 'Preview auto-score'),
    ('irg_apply_auto_score', 'Apply auto-score'),
    ('irg_preview_regrade_attempt', 'Preview regrade of one attempt'),
    ('irg_apply_regrade_attempt', 'Regrade one attempt'),
    ('irg_preview_feedback_import', 'Preview TXT feedback import'),
    ('irg_apply_feedback_import', 'Apply TXT feedback import'),
    ('irg_get_attachment_metadata', 'Read private attachment metadata'),
    ('irg_upload_private_attachment', 'Upload a private attachment'),
]

OPERATION_SPECS = {
    'irg_list_academic_periods': {'kind': 'read', 'keys': {'limit', 'offset'}},
    'irg_list_courses': {'kind': 'read', 'keys': {'limit', 'offset', 'name', 'code'}},
    'irg_get_course_overview': {'kind': 'read', 'keys': {'course_id'}},
    'irg_get_course_batches': {'kind': 'read', 'keys': {'course_id', 'limit', 'offset'}},
    'irg_list_subjects': {'kind': 'read', 'keys': {'course_id', 'limit', 'offset'}},
    'irg_get_course_structure': {'kind': 'read', 'keys': {'channel_id'}},
    'irg_get_slide': {'kind': 'read', 'keys': {'slide_id'}},
    'irg_get_admission_overview': {'kind': 'read', 'keys': {'admission_id'}},
    'irg_get_admission_subject_openings': {'kind': 'read', 'keys': {'admission_id'}},
    'irg_get_student_access': {'kind': 'read', 'keys': {'admission_id', 'partner_id'}},
    'irg_get_student_academic_360': {'kind': 'read', 'keys': {'admission_id'}},
    'irg_get_gradebook_summary': {'kind': 'read', 'keys': {'admission_id', 'partner_id'}},
    'irg_get_moodle_sync_status': {'kind': 'read', 'keys': {'course_id', 'admission_id'}},
    'irg_get_survey_structure': {'kind': 'read', 'keys': {'survey_id'}},
    'irg_get_academic_incidents': {'kind': 'read', 'keys': {'admission_id', 'course_id'}},
    'irg_create_slide_draft': {
        'kind': 'write',
        'keys': {'channel_id', 'name', 'html_content', 'sequence', 'irg_section_id', 'is_published'},
    },
    'irg_update_slide_draft': {
        'kind': 'write',
        'keys': {'slide_id', 'name', 'html_content', 'sequence', 'irg_section_id'},
    },
    'irg_create_course_section': {
        'kind': 'write',
        'keys': {'channel_id', 'name', 'sequence'},
    },
    'irg_reorder_course_section': {
        'kind': 'write',
        'keys': {'channel_id', 'section_ids'},
    },
    'irg_publish_slide': {'kind': 'write', 'keys': {'slide_id'}},
    'irg_unpublish_slide': {'kind': 'write', 'keys': {'slide_id'}},
    'irg_approve_operation': {'kind': 'meta', 'keys': {'operation_id'}},
    'irg_reject_operation': {'kind': 'meta', 'keys': {'operation_id'}},
    'irg_preview_online_clone': {'kind': 'read', 'keys': {'channel_id'}},
    'irg_apply_online_clone': {'kind': 'write', 'keys': {'channel_id'}},
    'irg_preview_content_reconciliation': {'kind': 'read', 'keys': {'channel_id'}},
    'irg_apply_content_reconciliation': {'kind': 'write', 'keys': {'channel_id'}},
    'irg_preview_subject_opening': {'kind': 'read', 'keys': {'admission_id'}},
    'irg_apply_subject_opening': {'kind': 'write', 'keys': {'admission_id'}},
    'irg_preview_access_reconciliation': {'kind': 'read', 'keys': {'admission_id'}},
    'irg_apply_access_reconciliation': {'kind': 'write', 'keys': {'admission_id'}},
    'irg_preview_enrollment': {'kind': 'read', 'keys': {'admission_id'}},
    'irg_apply_enrollment': {'kind': 'write', 'keys': {'admission_id'}},
    'irg_preview_withdrawal': {'kind': 'read', 'keys': {'admission_id'}},
    'irg_apply_withdrawal': {'kind': 'write', 'keys': {'admission_id'}},
    'irg_get_access_exceptions': {'kind': 'read', 'keys': {'admission_id'}},
    'irg_get_batch_schedule': {'kind': 'read', 'keys': {'batch_id'}},
    'irg_preview_batch_schedule_sync': {'kind': 'read', 'keys': {'batch_id', 'lines'}},
    'irg_apply_batch_schedule_sync': {'kind': 'write', 'keys': {'batch_id', 'lines'}},
    'irg_preview_subject_precedence': {'kind': 'read', 'keys': {'subject_id', 'admission_id'}},
    'irg_get_student_subject_eligibility': {'kind': 'read', 'keys': {'subject_id', 'admission_id'}},
    'irg_preview_moodle_course_mapping': {'kind': 'read', 'keys': {'maps'}},
    'irg_apply_moodle_course_mapping': {'kind': 'write', 'keys': {'maps'}},
    'irg_preview_moodle_grade_sync': {'kind': 'read', 'keys': {'course_id', 'admission_id'}},
    'irg_apply_moodle_grade_sync': {'kind': 'write', 'keys': {'course_id', 'admission_id'}},
    'irg_confirm_moodle_student_match': {
        'kind': 'write',
        'keys': {'grade_id', 'student_id'},
    },
    'irg_get_student_grade_evidence': {'kind': 'read', 'keys': {'admission_id', 'subject_id'}},
    'irg_create_survey_draft': {'kind': 'write', 'keys': {'title'}},
    'irg_update_survey_draft': {'kind': 'write', 'keys': {'survey_id', 'title'}},
    'irg_preview_auto_score': {'kind': 'read', 'keys': {'survey_id'}},
    'irg_apply_auto_score': {'kind': 'write', 'keys': {'survey_id'}},
    'irg_preview_regrade_attempt': {'kind': 'read', 'keys': {'user_input_id'}},
    'irg_apply_regrade_attempt': {'kind': 'write', 'keys': {'user_input_id'}},
    'irg_preview_feedback_import': {'kind': 'read', 'keys': {'survey_id', 'txt_content'}},
    'irg_apply_feedback_import': {'kind': 'write', 'keys': {'survey_id', 'txt_content'}},
    'irg_get_attachment_metadata': {'kind': 'read', 'keys': {'attachment_id'}},
    'irg_upload_private_attachment': {
        'kind': 'write',
        'keys': {'res_model', 'res_id', 'name', 'mimetype', 'file_b64'},
    },
}
