# -*- coding: utf-8 -*-
{
    'name': 'IRG TFM Convocatorias',
    'version': '16.0.1.0.1',
    'summary': 'Activa y administra convocatorias de Trabajo Final de Máster',
    'category': 'Education',
    'author': 'IRG',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'openeducat_core',
        'isep_student_filter',
        'isep_gradebook',
        'website_slides',
        'isep_tesis_model',
        'irg_course_portal_tiles',
        'irg_course_portal_tiles_diplomado_hide',
        'irg_batch_slide_restrictions',
        'irg_practice_slide_restrictions',
        'irg_elearning_editable_sections',
        'irg_auto_enroll_cron_robust',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'views/irg_tfm_convocatoria_views.xml',
        'views/op_course_views.xml',
        'views/tesis_model_views.xml',
        'views/tfm_portal_templates.xml',
        'views/slide_tfm_views.xml',
        'views/tfm_slide_templates.xml',
    ],
    'pre_init_hook': 'pre_init_hook',
    'installable': True,
    'application': False,
}
