# Part of Odoo. See LICENSE file for full copyright and licensing details.

SUPPORTED_CURRENCIES = [
    "AED", "AFN", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", 
    "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTN", "BWP", "BZD", "CAD", 
    "CDF", "CHF", "CLP", "CNH", "CNY", "COP", "CRC", "CVE", "CZK", "DJF", "DKK", "DOP", 
    "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", 
    "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "INR", "ISK", 
    "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KRW", "KWD", "KYD", "KZT", "LAK", 
    "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", 
    "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", 
    "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RWF", 
    "SAR", "SBD", "SCR", "SEK", "SGD", "SHP", "SLL", "SOS", "SRD", "STD", "SZL", "THB", 
    "TJS", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", 
    "VND", "VUV", "WST", "XAF", "XCD", "XOF", "XPF", "YER", "ZAR", "ZMW"
]

CURRENCIES = {
        "AED": {"name": "United Arab Emirates Dirhams", "unit": 100},
        "AFN": {"name": "Afghan afghanis", "unit": 100},
        "AMD": {"name": "Armenian drams", "unit": 100},
        "ANG": {"name": "Netherlands Antillean guilders", "unit": 100},
        "AOA": {"name": "Angolan kwanzas", "unit": 100},
        "ARS": {"name": "Argentine pesos", "unit": 100},
        "AUD": {"name": "Australian Dollars", "unit": 100},
        "AWG": {"name": "Aruban florin", "unit": 100},
        "AZN": {"name": "Azerbaijani Manat", "unit": 100},
        "BAM": {"name": "Bosnia and Herzegovina convertible marks", "unit": 100},
        "BBD": {"name": "Barbadian dollars", "unit": 100},
        "BDT": {"name": "Bangladeshi takas", "unit": 100},
        "BGN": {"name": "Bulgarian Levs", "unit": 100},
        "BHD": {"name": "Bahraini Dinars", "unit": 1000},
        "BIF": {"name": "Burundian franc", "unit": 100},
        "BMD": {"name": "Bermudian Dollars", "unit": 100},
        "BND": {"name": "Brunei dollar", "unit": 100},
        "BOB": {"name": "Bolivian Bolivianos", "unit": 100},
        "BRL": {"name": "Brazilian Reals", "unit": 100},
        "BSD": {"name": "Bahamian Dollars", "unit": 100},
        "BTN": {"name": "Bhutanese ngultrum", "unit": 100},
        "BWP": {"name": "Botswana pula", "unit": 100},
        "BZD": {"name": "Belize dollars", "unit": 100},
        "CAD": {"name": "Canadian Dollars", "unit": 100},
        "CDF": {"name": "Congolese francs", "unit": 100},
        "CHF": {"name": "Swiss Francs", "unit": 100},
        "CLP": {"name": "Chilean pesos", "unit": 1},
        "CNH": {"name": "Chinese Yuan (Offshore) Renminbi", "unit": 100},
        "CNY": {"name": "Chinese Yuan Renminbi", "unit": 100},
        "COP": {"name": "Colombian pesos", "unit": 100},
        "CRC": {"name": "Costa Rican colones", "unit": 100},
        "CVE": {"name": "Cape Verdean escudos", "unit": 100},
        "CZK": {"name": "Czech Korunas", "unit": 100},
        "DJF": {"name": "Djiboutian francs", "unit": 100},
        "DKK": {"name": "Danish Kroner", "unit": 100},
        "DOP": {"name": "Dominican pesos", "unit": 100},
        "DZD": {"name": "Algerian dinars", "unit": 100},
        "EGP": {"name": "Egyptian pounds", "unit": 100},
        "ERN": {"name": "Eritrean Nakfas", "unit": 100},
        "ETB": {"name": "Ethiopian Birrs", "unit": 100},
        "EUR": {"name": "Euros", "unit": 100},
        "FJD": {"name": "Fijian Dollars", "unit": 100},
        "FKP": {"name": "Falkland Islands pounds", "unit": 100},
        "GBP": {"name": "British Pounds", "unit": 100},
        "GEL": {"name": "Georgian lari", "unit": 100},
        "GHS": {"name": "Ghana cedis", "unit": 100},
        "GIP": {"name": "Gibraltar Pounds", "unit": 100},
        "GMD": {"name": "Gambian dalasis", "unit": 100},
        "GNF": {"name": "Guinean francs", "unit": 100},
        "GTQ": {"name": "Guatemalan Quetzals", "unit": 100},
        "GYD": {"name": "Guyanaese Dollars", "unit": 100},
        "HKD": {"name": "Hong Kong Dollars", "unit": 100},
        "HNL": {"name": "Honduran lempiras", "unit": 100},
        "HRK": {"name": "Croatian Kunas", "unit": 100},
        "HTG": {"name": "Haitian gourdes", "unit": 100},
        "HUF": {"name": "Hungarian Forints", "unit": 100},
        "IDR": {"name": "Indonesian Rupiahs", "unit": 100},
        "ILS": {"name": "Israeli New Sheqels", "unit": 100},
        "INR": {"name": "Indian Rupees", "unit": 100},
        "ISK": {"name": "Icelandic krónur", "unit": 100},
        "JMD": {"name": "Jamaican dollars", "unit": 100},
        "JOD": {"name": "Jordanian Dinars", "unit": 100},
        "JPY": {"name": "Japanese Yen", "unit": 1},
        "KES": {"name": "Kenyan Shillings", "unit": 100},
        "KGS": {"name": "Kyrgyzstani Som", "unit": 100},
        "KHR": {"name": "Cambodian Riels", "unit": 100},
        "KMF": {"name": "Comorian francs", "unit": 100},
        "KRW": {"name": "South Korean Won", "unit": 100},
        "KWD": {"name": "Kuwaiti Dinars", "unit": 1000},
        "KYD": {"name": "Cayman Island Dollars", "unit": 100},
        "KZT": {"name": "Kazakhstani tenge", "unit": 100},
        "LAK": {"name": "Lao kip", "unit": 100},
        "LBP": {"name": "Lebanese Pounds", "unit": 100},
        "LKR": {"name": "Sri Lankan rupees", "unit": 100},
        "LRD": {"name": "Liberian dollars", "unit": 100},
        "LSL": {"name": "Lesotho maloti", "unit": 100},
        "LYD": {"name": "Libyan Dinars", "unit": 1000},
        "MAD": {"name": "Moroccan Dirhams", "unit": 100},
        "MDL": {"name": "Moldovan lei", "unit": 100},
        "MGA": {"name": "Malagasy ariary", "unit": 5},
        "MKD": {"name": "Macedonian denari", "unit": 100},
        "MMK": {"name": "Myanmar kyat", "unit": 100},
        "MNT": {"name": "Mongolian tugriks", "unit": 100},
        "MOP": {"name": "Macau Patacas", "unit": 100},
        "MUR": {"name": "Mauritian Rupees", "unit": 100},
        "MVR": {"name": "Maldivian Rufiyaas", "unit": 100},
        "MWK": {"name": "Malawian kwachas", "unit": 100},
        "MXN": {"name": "Mexican Pesos", "unit": 100},
        "MYR": {"name": "Malaysian Ringgits", "unit": 100},
        "MZN": {"name": "Mozambican meticais", "unit": 100},
        "NAD": {"name": "Namibian Dollars", "unit": 100},
        "NGN": {"name": "Nigerian Naira", "unit": 100},
        "NIO": {"name": "Nicaraguan córdobas", "unit": 100},
        "NOK": {"name": "Norwegian Kroner", "unit": 100},
        "NPR": {"name": "Nepalese rupees", "unit": 100},
        "NZD": {"name": "New Zealand Dollars", "unit": 100},
        "OMR": {"name": "Omani Rials", "unit": 1000},
        "PAB": {"name": "Panamanian Balboas", "unit": 100},
        "PEN": {"name": "Peruvian Nuevo Sols", "unit": 100},
        "PGK": {"name": "Papua New Guinean kina", "unit": 100},
        "PHP": {"name": "Philippine Pisos", "unit": 100},
        "PKR": {"name": "Pakistani rupees", "unit": 100},
        "PLN": {"name": "Polish złoties", "unit": 100},
        "PYG": {"name": "Paraguayan guaranies", "unit": 100},
        "QAR": {"name": "Qatari Riyals", "unit": 100},
        "RON": {"name": "Romanian Leus", "unit": 100},
        "RSD": {"name": "Serbian Dinars", "unit": 100},
        "RWF": {"name": "Rwandan francs", "unit": 100},
        "SAR": {"name": "Saudi Riyals", "unit": 100},
        "SBD": {"name": "Solomon Islands dollars", "unit": 100},
        "SCR": {"name": "Seychellois rupees", "unit": 100},
        "SEK": {"name": "Swedish Kronor", "unit": 100},
        "SGD": {"name": "Singapore Dollars", "unit": 100},
        "SHP": {"name": "Saint Helena pounds", "unit": 100},
        "SLL": {"name": "Sierra Leonean leones", "unit": 100},
        "SOS": {"name": "Somali shillings", "unit": 100},
        "SRD": {"name": "Surinamese dollars", "unit": 100},
        "STD": {"name": "São Tomé and Príncipe dobras", "unit": 100},
        "SZL": {"name": "Swazi Lilangenis", "unit": 100},
        "THB": {"name": "Thai Bahts", "unit": 100},
        "TJS": {"name": "Tajikistani somoni", "unit": 100},
        "TND": {"name": "Tunisian Dinars", "unit": 1000},
        "TOP": {"name": "Tongan paʻanga", "unit": 100},
        "TRY": {"name": "Turkish Liras", "unit": 100},
        "TTD": {"name": "Trinidad and Tobago Dollars", "unit": 100},
        "TWD": {"name": "New Taiwan Dollars", "unit": 100},
        "TZS": {"name": "Tanzanian shillings", "unit": 100},
        "UAH": {"name": "Ukrainian Hryvnia", "unit": 100},
        "UGX": {"name": "Ugandan shillings", "unit": 100},
        "USD": {"name": "United States Dollars", "unit": 100},
        "UYU": {"name": "Uruguayan pesos", "unit": 100},
        "UZS": {"name": "Uzbekistan So'm", "unit": 100},
        "VND": {"name": "Vietnamese Dong", "unit": 10},
        "VUV": {"name": "Vanuatu vatu", "unit": 1},
        "WST": {"name": "Samoan tālā", "unit": 100},
        "XAF": {"name": "CFA francs", "unit": 100},
        "XCD": {"name": "East Caribbean dollars", "unit": 100},
        "XOF": {"name": "West African CFA francs", "unit": 100},
        "XPF": {"name": "French Pacific Francs", "unit": 100},
        "YER": {"name": "Yemeni Rials", "unit": 100},
        "ZAR": {"name": "South African Rands", "unit": 100},
        "ZMW": {"name": "Zambian kwacha", "unit": 100}
    }


# Mapping of transaction states to Flywire payment statuses.
PAYMENT_STATUS_MAPPING = {
    'pending': ['pending auth'],
    'done': ['successful'],
    'cancel': ['cancelled'],
    'error': ['failed'],
}

# The codes of the payment methods to activate when Flywire is activated.
DEFAULT_PAYMENT_METHODS_CODES = [
    # Primary payment methods.
    'card',
    'mpesa',
    'visa',
    'mastercard',
    'amex',
]

PAYMENT_METHODS_MAPPING = {
    'bank_transfer': 'banktransfer',
}
