# -*- coding: utf-8 -*-
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html

{
    "name": "Adaptacion de Funcionalidades Academicas y de Facturacion IRG",
    "version": "16.0.1.0.0",
    "author": "FantasticoLab",
    "website": "https://www.fantasticolab.com",
    "category": "CRM",
    "license": "AGPL-3",
    "depends": [
        "base",
        "website_mail",
        "mail",
        "crm",
        "sale",
        "isep_control_escolar", 
        "isep_openeducat_custom", 
        "isep_record_request_extended", 
        "isep_student_access", 
        "isep_student_filter", 
        "openeducat_activity", 
        "openeducat_alumni_enterprise", 
        "openeducat_assignment", 
        "openeducat_attendance", 
        "openeducat_core", 
        "openeducat_core_enterprise", 
        "openeducat_fees", 
        "openeducat_job_enterprise", 
        "openeducat_job_skill_bridge", 
        "openeducat_parent", 
        "openeducat_placement_enterprise", 
        "openeducat_skill_enterprise", 
        "openeducat_student_attendance_enterprise",
        "openeducat_fees",
        #"voip",
        #"isep_custom",
        #"hspl_user_simulation",
    ],
    "data": [
         #"security/ir.model.access.csv",
         "views/account_move.xml",
         "views/op_student.xml",
         "views/op_admission_register.xml",
    #     "views/voip_phonecall.xml",
    #
    ],
    'installable': True,
}
